In [22]:
import pandas as pd
import numpy as np
import json
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 150)

MARKET = "eth_cbbtc_usdc"
EVENTS_PATH = "/Users/yegortrussov/Documents/ml/lending_protocols/dataset_collection/data/markets_labelled"
HOURLY_MARKET_PATH = "/Users/yegortrussov/Documents/ml/lending_protocols/dataset_collection/data/markets_hourly_data"

df = pd.read_csv(f"{EVENTS_PATH}/{MARKET}.csv")
market_df = pd.read_csv(f"{HOURLY_MARKET_PATH}/{MARKET}.csv")

df.head(2)

,hash,type,timestamp,user_address,assets,assets_usd,liquidated_assets,liquidated_assets_usd,market,datetime,market_address,total_supply_before,total_borrow_before,total_supply_after,total_borrow_after,utilization_before,utilization_after,tx_actions,borrow_rate_before,supply_rate_before,borrow_rate_after,supply_rate_after,collateral_price,loan_asset_price,collateral_before,collateral_value_before,debt_before,supply_before,ltv_before,collateral_after,collateral_value_after,debt_after,supply_after,ltv_after,health_factor_before,health_factor_after,event_type,vault_flg,volatility_1h,drawdown_1h,trend_1h,volatility_6h,drawdown_6h,trend_6h,volatility_24h,drawdown_24h,trend_24h,hash_short,event_sequence_type
0,0xcbf9186fe08ab70d98098d274e46f380248321e1bc07...,MarketSupply,1757435615,0x0000000000000000000000000000000000000001,1100000,1.099788,0,0.0,eth_cbbtc_usdc,2025-09-09 16:33:35,0x64d65c9a2d91c36d56fbc42d69e979335320169b3df6...,4.708136e+08,3.763097e+08,4.708139e+08,3.763100e+08,0.799275,0.799275,1,0.041319,0.033026,0.041319,0.033026,111014.000000,0.999803,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.099783,0.0,0.0,0.0,loan_position_supply,False,0,0,0,0.003739,0.0,-0.015004,0.003234,0.000000,-0.012060,0xcbf9186f,loan_position_supply
1,0xc7938048f930dcad275757ef6531bc27cce264d6cead...,MarketSupply,1761595235,0x000000000000000000000000000000000000dEaD,10586,0.010585,0,0.0,eth_cbbtc_usdc,2025-10-27 20:00:35,0x64d65c9a2d91c36d56fbc42d69e979335320169b3df6...,4.769922e+08,4.168996e+08,4.769930e+08,4.169004e+08,0.874018,0.874018,1,0.044545,0.038934,0.044545,0.038934,114836.091413,0.999801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.010584,0.0,0.0,0.0,loan_position_supply,False,0,0,0,0.004437,0.0,-0.000236,0.003686,-0.012068,0.011874,0xc7938048,loan_position_supply

,datetime,type,total_borrow_before,total_borrow_after,vault_flg
2976,2025-09-20 15:03:35,MarketWithdraw,4.057149e+08,4.057158e+08,False
3000,2025-09-30 19:39:23,MarketWithdraw,3.590746e+08,3.590748e+08,False
3017,2025-10-03 19:37:35,MarketWithdraw,4.267607e+08,4.267608e+08,False
3027,2025-10-05 15:12:11,MarketWithdraw,4.259398e+08,4.259399e+08,False
3057,2025-10-10 18:00:59,MarketWithdraw,4.004634e+08,4.004634e+08,False
...,...,...,...,...,...
59907,2026-01-07 11:33:47,MarketWithdraw,3.949392e+08,3.949392e+08,True
59922,2026-01-07 21:40:47,MarketWithdraw,4.001772e+08,4.001772e+08,True
59951,2026-01-08 08:32:59,MarketWithdraw,4.000759e+08,4.000759e+08,True
59953,2026-01-08 09:40:47,MarketWithdraw,4.000779e+08,4.000780e+08,True
59999,2026-01-09 12:41:23,MarketWithdraw,4.126194e+08,4.126194e+08,True

In [12]:
def detect_utilization_shocks(hourly_df, threshold=0.1, cutoff_date=None):
    df = hourly_df.sort_values('timestamp').copy()
    df['utilization_change'] = df['utilization'].diff()
    df['utilization_change_abs'] = df['utilization_change'].abs()
    df['is_shock'] = df['utilization_change_abs'] > threshold
    
    if cutoff_date:
        cutoff_ts = int(pd.Timestamp(cutoff_date).timestamp())
        df = df[df['timestamp'] > cutoff_ts]
    
    shock_df = df[df['is_shock']]
    return list(zip(shock_df['timestamp'], shock_df['utilization_change']))
shocks = detect_utilization_shocks(
    market_df,
    cutoff_date="2025-11-01",
)
shocks

[(1761958800, -0.1351587662174918),
 (1762293600, -0.11612628981366202),
 (1762466400, 0.11474145336777308),
 (1767056400, -0.14718934048721644),
 (1767117600, 0.10591637078203686),
 (1767142800, -0.23557347346019586),
 (1767193200, 0.23331363575815378),
 (1767981600, -0.13075056354368286)]

In [28]:
ts = 1762466400
df[
    # (df["utilization_after"] - df["utilization_before"] > 0.01) &
    (df["timestamp"] > ts - 2*3600) &
    (df["timestamp"] < ts + 6*3600)
][[
    "datetime",
    "hash_short",
    "user_address",
    "type",
    "utilization_before",
    "utilization_after",
    "vault_flg",
    "borrow_rate_after",
    "debt_after",
    "supply_after"
]].sort_values("datetime")[:90]

,datetime,hash_short,user_address,type,utilization_before,utilization_after,vault_flg,borrow_rate_after,debt_after,supply_after
12103,2025-11-06 20:03:23,0x4154a5a6,0x7204B7Dbf9412567835633B6F00C3Edc3a8D6330,MarketWithdraw,0.846240,0.846240,True,0.041763,0.000000e+00,-2.426975e+04
47140,2025-11-06 20:03:59,0x8110bf64,0xBEefb9f61CC44895d8AEc381373555a64191A9c4,MarketWithdraw,0.846240,0.857396,True,0.042170,0.000000e+00,-5.118589e+05
47141,2025-11-06 20:03:59,0x8110bf64,0xBEefb9f61CC44895d8AEc381373555a64191A9c4,MarketSupply,0.846240,0.857396,True,0.042170,0.000000e+00,-5.118589e+05
39339,2025-11-06 20:11:59,0x44a42c62,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.857396,0.857396,True,0.042170,0.000000e+00,1.297028e+06
39340,2025-11-06 20:13:35,0x11d8cf80,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.857396,0.857389,True,0.042170,0.000000e+00,1.301079e+06
39341,2025-11-06 20:16:59,0x1f662ee3,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.857389,0.856505,True,0.042137,0.000000e+00,1.798107e+06
18921,2025-11-06 20:22:35,0xd5e22598,0xBA10248Ac4DCC76ef27b58Aad637F02A27FBc4f6,MarketWithdrawCollateral,0.856507,0.856507,False,0.042137,5.648965e+05,0.000000e+00
16746,2025-11-06 20:22:35,0x420163b4,0x974c8FBf4fd795F66B85B73ebC988A51F1A040a9,MarketWithdraw,0.856505,0.856507,True,0.042137,0.000000e+00,2.807137e+07
8265,2025-11-06 20:24:11,0xd5d51902,0x62fE596d59fB077c2Df736dF212E0AFfb522dC78,MarketSupply,0.856507,0.855265,True,0.042092,0.000000e+00,6.991992e+05
47142,2025-11-06 20:29:11,0xf9db4f8b,0xBEefb9f61CC44895d8AEc381373555a64191A9c4,MarketSupply,0.855265,0.855259,True,0.042092,0.000000e+00,-5.085000e+05
39342,2025-11-06 20:29:23,0x827e8515,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.855259,0.855153,True,0.042088,0.000000e+00,1.858096e+06
56608,2025-11-06 20:31:47,0x1168bf43,0xdd0f28e19C1780eb6396170735D45153D261490d,MarketSupply,0.855153,0.855100,True,0.042086,0.000000e+00,4.864551e+07
39343,2025-11-06 20:31:47,0xa8c68a8a,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.855100,0.855011,True,0.042083,0.000000e+00,1.908241e+06
39344,2025-11-06 20:33:11,0x59a62dc9,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.855011,0.832301,True,0.041255,0.000000e+00,1.508767e+07
56609,2025-11-06 20:34:47,0x0535ceac,0xdd0f28e19C1780eb6396170735D45153D261490d,MarketSupply,0.832301,0.832039,True,0.041246,0.000000e+00,4.880222e+07
12945,2025-11-06 20:36:11,0x6ecfbef6,0x85BD59D3AB7BEc72564e4F3C55067DD74Dc7074c,MarketWithdrawCollateral,0.832039,0.832039,False,0.041246,5.461420e+03,0.000000e+00
39345,2025-11-06 20:36:35,0xbb748964,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketWithdraw,0.832039,0.834898,True,0.041350,0.000000e+00,1.338763e+07
47143,2025-11-06 20:39:59,0x96dc1dd9,0xBEefb9f61CC44895d8AEc381373555a64191A9c4,MarketWithdraw,0.834898,0.834898,True,0.041350,0.000000e+00,-5.085345e+05
39346,2025-11-06 20:51:11,0xf4ac7488,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.834898,0.834890,True,0.041350,0.000000e+00,1.339263e+07
14135,2025-11-06 20:51:47,0xa3b4a856,0x8eB67A509616cd6A7c1B3c8C21D48FF57df3d458,MarketWithdraw,0.834890,0.834947,True,0.041352,0.000000e+00,3.300553e+06
31400,2025-11-06 20:58:11,0x1142648e,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketWithdraw,0.834947,0.834959,True,0.041352,0.000000e+00,3.516191e+08
8266,2025-11-06 20:58:11,0x1142648e,0x62fE596d59fB077c2Df736dF212E0AFfb522dC78,MarketWithdraw,0.834947,0.834959,True,0.041352,0.000000e+00,6.965648e+05
12286,2025-11-06 20:58:59,0x2ea78a05,0x73384DF5e469dd98f27edb0Bc3b2d5415C95E651,MarketRepay,0.834959,0.834953,False,0.041352,1.678604e+04,0.000000e+00
31401,2025-11-06 20:59:59,0xfc1beadc,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.834953,0.834855,True,0.041348,0.000000e+00,3.516772e+08
51094,2025-11-06 21:06:35,0x955b6008,0xbCd16D361adf5E7e0dc0010756B49666b4f38eE0,MarketSupplyCollateral,0.834855,0.981594,False,0.150711,2.014634e+08,0.000000e+00
31402,2025-11-06 21:06:35,0x955b6008,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.834855,0.981594,True,0.150711,0.000000e+00,3.794366e+08
14136,2025-11-06 21:06:35,0x955b6008,0x8eB67A509616cd6A7c1B3c8C21D48FF57df3d458,MarketSupply,0.834855,0.981594,True,0.150711,0.000000e+00,3.451605e+06
51095,2025-11-06 21:06:35,0x955b6008,0xbCd16D361adf5E7e0dc0010756B49666b4f38eE0,MarketBorrow,0.834855,0.981594,False,0.150711,2.014634e+08,0.000000e+00
12104,2025-11-06 21:06:35,0x955b6008,0x7204B7Dbf9412567835633B6F00C3Edc3a8D6330,MarketSupply,0.834855,0.981594,True,0.150711,0.000000e+00,-2.427051e+04
31403,2025-11-06 21:06:59,0xe8eecc44,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.981594,0.973847,True,0.140551,0.000000e+00,3.835942e+08
6236,2025-11-06 21:10:35,0x2fc238bf,0x43Ee0243eA8CF02f7087d8B16C8D2007CC9c7cA2,MarketSupply,0.973847,0.973147,False,0.139633,0.000000e+00,3.778135e+05
31404,2025-11-06 21:10:59,0x7ecbdd10,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketWithdraw,0.973147,0.973148,True,0.139634,0.000000e+00,3.835937e+08
39347,2025-11-06 21:13:35,0x78dd718d,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.973148,0.955107,True,0.115976,0.000000e+00,2.334947e+07
12105,2025-11-06 21:15:35,0xc0f2b5a7,0x7204B7Dbf9412567835633B6F00C3Edc3a8D6330,MarketWithdraw,0.955107,0.955107,True,0.115976,0.000000e+00,-2.427054e+04
7835,2025-11-06 21:16:47,0x02dca08b,0x5b56F90340dBAa6a8693DADb141D620f0e154fE6,MarketSupply,0.955107,0.950834,False,0.110373,0.000000e+00,5.702455e+06
39348,2025-11-06 21:21:47,0x0504aa68,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.950834,0.950639,True,0.110117,0.000000e+00,2.345998e+07
18922,2025-11-06 21:25:11,0x805a45bc,0xBA10248Ac4DCC76ef27b58Aad637F02A27FBc4f6,MarketRepay,0.950639,0.949713,False,0.108903,6.499021e+04,0.000000e+00
18923,2025-11-06 21:25:11,0x805a45bc,0xBA10248Ac4DCC76ef27b58Aad637F02A27FBc4f6,MarketWithdrawCollateral,0.950639,0.949713,False,0.108903,6.499021e+04,0.000000e+00
39349,2025-11-06 21:25:47,0x80744498,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.949713,0.949711,True,0.108901,0.000000e+00,2.346085e+07
39350,2025-11-06 21:26:23,0xe1863b00,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.949711,0.949709,True,0.108898,0.000000e+00,2.346185e+07
18924,2025-11-06 21:28:11,0x06887b76,0xBA10248Ac4DCC76ef27b58Aad637F02A27FBc4f6,MarketRepay,0.949709,0.949550,False,0.108689,-2.117921e+04,0.000000e+00
18925,2025-11-06 21:28:11,0x06887b76,0xBA10248Ac4DCC76ef27b58Aad637F02A27FBc4f6,MarketWithdrawCollateral,0.949709,0.949550,False,0.108689,-2.117921e+04,0.000000e+00
7321,2025-11-06 21:29:23,0xeaec2116,0x559458Aac63528fB18893d797FF223dF4D5fa3C9,MarketRepay,0.949550,0.948669,False,0.107535,3.707638e+06,0.000000e+00
7322,2025-11-06 21:31:59,0x083021df,0x559458Aac63528fB18893d797FF223dF4D5fa3C9,MarketWithdrawCollateral,0.948669,0.948669,False,0.107535,3.707639e+06,0.000000e+00
56610,2025-11-06 21:33:23,0x82383968,0xdd0f28e19C1780eb6396170735D45153D261490d,MarketWithdraw,0.948669,0.957904,True,0.119645,0.000000e+00,4.360014e+07
56611,2025-11-06 21:33:23,0x82383968,0xdd0f28e19C1780eb6396170735D45153D261490d,MarketSupply,0.948669,0.957904,True,0.119645,0.000000e+00,4.360014e+07
195,2025-11-06 21:33:47,0x7a5219c1,0x018f8f5F52AAfF23FF838aE4637aFe22713FB428,MarketSupply,0.957904,0.957778,False,0.119480,0.000000e+00,7.011321e+04
7836,2025-11-06 21:36:35,0xb2098fef,0x5b56F90340dBAa6a8693DADb141D620f0e154fE6,MarketSupply,0.957778,0.953684,False,0.114111,0.000000e+00,7.996905e+06
39351,2025-11-06 21:37:59,0xbf74e9b3,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.953684,0.953507,True,0.113878,0.000000e+00,2.356184e+07
31405,2025-11-06 21:38:11,0x4829fbc4,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.953507,0.953503,True,0.113873,0.000000e+00,3.835948e+08
39352,2025-11-06 21:38:11,0x4829fbc4,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.953507,0.953503,True,0.113873,0.000000e+00,2.356317e+07
31406,2025-11-06 21:40:47,0xc8498400,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.953503,0.953502,True,0.113872,0.000000e+00,3.835952e+08
14137,2025-11-06 21:42:47,0xfbd9436d,0x8eB67A509616cd6A7c1B3c8C21D48FF57df3d458,MarketSupply,0.953502,0.952147,True,0.112095,0.000000e+00,4.215727e+06
31407,2025-11-06 21:43:47,0x50782a86,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.952147,0.952147,True,0.112095,0.000000e+00,3.835953e+08
7323,2025-11-06 21:44:11,0x2e4162e5,0x559458Aac63528fB18893d797FF223dF4D5fa3C9,MarketRepay,0.952147,0.950473,False,0.109900,2.807774e+06,0.000000e+00
39353,2025-11-06 21:49:47,0xd6f042a8,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.950473,0.949561,True,0.108704,0.000000e+00,2.407962e+07
31408,2025-11-06 21:50:47,0x7aa1e165,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.949561,0.949473,True,0.108588,0.000000e+00,3.836453e+08
31409,2025-11-06 21:51:59,0xddd82a86,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.949473,0.949335,True,0.108408,0.000000e+00,3.837232e+08
31410,2025-11-06 21:53:59,0x05e96b44,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.949335,0.949312,True,0.108377,0.000000e+00,3.837364e+08
31411,2025-11-06 21:56:11,0xadbbdb17,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketWithdraw,0.949312,0.951964,True,0.111855,0.000000e+00,3.822366e+08
47144,2025-11-06 21:56:23,0x327f3c31,0xBEefb9f61CC44895d8AEc381373555a64191A9c4,MarketWithdraw,0.951964,0.951973,True,0.111867,0.000000e+00,-5.135071e+05
7324,2025-11-06 21:56:47,0x0a47a8ca,0x559458Aac63528fB18893d797FF223dF4D5fa3C9,MarketRepay,0.951973,0.950137,False,0.109460,1.822408e+06,0.000000e+00
47145,2025-11-06 21:57:47,0x33d74e18,0xBEefb9f61CC44895d8AEc381373555a64191A9c4,MarketWithdraw,0.950137,0.950139,True,0.109462,0.000000e+00,-5.145133e+05
31412,2025-11-06 21:58:35,0xc639574e,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.950139,0.949609,True,0.108767,0.000000e+00,3.823865e+08
56612,2025-11-06 21:58:35,0xc639574e,0xdd0f28e19C1780eb6396170735D45153D261490d,MarketSupply,0.950139,0.949609,True,0.108767,0.000000e+00,4.374997e+07
7325,2025-11-06 21:58:35,0xca53b3b9,0x559458Aac63528fB18893d797FF223dF4D5fa3C9,MarketWithdrawCollateral,0.949609,0.949609,False,0.108767,1.822408e+06,0.000000e+00
31413,2025-11-06 21:59:11,0xc82218ac,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.949609,0.949596,True,0.108750,0.000000e+00,3.823937e+08
31414,2025-11-06 22:02:35,0xcfa3303e,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketWithdraw,0.949596,0.961107,True,0.124293,0.000000e+00,3.759612e+08
56613,2025-11-06 22:02:59,0x8c29edba,0xdd0f28e19C1780eb6396170735D45153D261490d,MarketSupply,0.961107,0.959535,True,0.122224,0.000000e+00,4.461961e+07
18569,2025-11-06 22:03:35,0x6309eb01,0xAe86261C403E8Da7B71Dcd3343ED9F1c8A972d63,MarketWithdraw,0.959535,0.959615,False,0.122329,0.000000e+00,5.465596e+05
18570,2025-11-06 22:03:35,0x6309eb01,0xAe86261C403E8Da7B71Dcd3343ED9F1c8A972d63,MarketSupply,0.959535,0.959615,False,0.122329,0.000000e+00,5.465596e+05
9626,2025-11-06 22:04:23,0x6b57ba61,0x68Aea7b82Df6CcdF76235D46445Ed83f85F845A3,MarketWithdraw,0.959615,0.959677,True,0.122411,0.000000e+00,1.654062e+07
7326,2025-11-06 22:04:35,0x3881b4eb,0x559458Aac63528fB18893d797FF223dF4D5fa3C9,MarketRepay,0.959677,0.956170,False,0.117796,-4.132855e+04,0.000000e+00
31415,2025-11-06 22:05:11,0xbcbebf26,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.956170,0.956169,True,0.117794,0.000000e+00,3.759618e+08
7327,2025-11-06 22:05:59,0xd7ceb686,0x559458Aac63528fB18893d797FF223dF4D5fa3C9,MarketWithdrawCollateral,0.956169,0.956169,False,0.117794,-4.132855e+04,0.000000e+00
56614,2025-11-06 22:07:23,0xa0ece428,0xdd0f28e19C1780eb6396170735D45153D261490d,MarketSupply,0.956169,0.956169,True,0.117794,0.000000e+00,4.461966e+07
39354,2025-11-06 22:07:47,0xa1da2845,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.956169,0.956144,True,0.117761,0.000000e+00,2.408362e+07
31416,2025-11-06 22:07:47,0xa1da2845,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.956169,0.956144,True,0.117761,0.000000e+00,3.759718e+08
14138,2025-11-06 22:08:47,0xff2898d3,0x8eB67A509616cd6A7c1B3c8C21D48FF57df3d458,MarketWithdraw,0.956144,0.956415,True,0.118119,0.000000e+00,4.064823e+06
56615,2025-11-06 22:09:35,0x81c98c8f,0xdd0f28e19C1780eb6396170735D45153D261490d,MarketSupply,0.956415,0.956236,True,0.117882,0.000000e+00,4.471965e+07
39355,2025-11-06 22:10:11,0xee5bbe93,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.956236,0.954320,True,0.115361,0.000000e+00,2.515027e+07
31417,2025-11-06 22:11:59,0x58bbca0f,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.954320,0.953667,True,0.114501,0.000000e+00,3.763365e+08
31418,2025-11-06 22:14:11,0xc7c053d0,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.953667,0.953666,True,0.114500,0.000000e+00,3.763372e+08
56616,2025-11-06 22:16:11,0x74ce7f70,0xdd0f28e19C1780eb6396170735D45153D261490d,MarketSupply,0.953666,0.953665,True,0.114499,0.000000e+00,4.471986e+07
56617,2025-11-06 22:17:35,0xdfed8e5f,0xdd0f28e19C1780eb6396170735D45153D261490d,MarketSupply,0.953665,0.953297,True,0.114015,0.000000e+00,4.492574e+07
39356,2025-11-06 22:20:11,0xbe3775cd,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.953297,0.951433,True,0.111561,0.000000e+00,2.619462e+07
47146,2025-11-06 22:21:11,0xeebe0c69,0xBEefb9f61CC44895d8AEc381373555a64191A9c4,MarketWithdraw,0.951433,0.951455,True,0.111590,0.000000e+00,-5.266825e+05
56618,2025-11-06 22:23:47,0xd96101e5,0xdd0f28e19C1780eb6396170735D45153D261490d,MarketSupply,0.951455,0.951277,True,0.111355,0.000000e+00,4.502579e+07
31419,2025-11-06 22:24:11,0x271bacba,0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB,MarketSupply,0.951277,0.951271,True,0.111348,0.000000e+00,3.763402e+08
39357,2025-11-06 22:24:23,0xb6850772,0xBEeFFF209270748ddd194831b3fa287a5386f5bC,MarketSupply,0.951271,0.951202,True,0.111257,0.000000e+00,2.623362e+07

In [ ]:
addrs = [
    "0xbCd16D361adf5E7e0dc0010756B49666b4f38eE0",
    "0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB"
]